=== bmatsuo/resume/resume.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="urn:resume"
           targetNamespace="urn:resume"
           elementFormDefault="qualified">
    <xs:element name="resume" type="Resume"/>
    
    <xs:complexType name="Resume">
        <xs:sequence>
            <xs:element name="header" type="Header"/>
            <xs:element name="objective" type="TextBody"/>
            <xs:element name="skills" type="Skills" maxOccurs="unbounded"/>
            <xs:element name="interests" type="Interests" maxOccurs="unbounded"/>
            <xs:element name="history" type="History"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Header">
        <xs:sequence>
            <xs:element name="name" type="Name"/>
            <xs:element name="contact" type="Contact"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="Name">
        <!-- should this be mixed content w/ tagged pieces? -->
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="collapse"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Link">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="href" type="HttpUri"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="Contact">
        <xs:sequence>
            <xs:element name="email" type="Email"/>
            <xs:element name="phone" type="Phone" minOccurs="0"/>
            <xs:element name="address" type="Address" minOccurs="0"/>
            <xs:element name="link" type="Link" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Address">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Modeled after the Portable Contacts specification
                http://portablecontacts.net/draft-spec.html#address_element
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="streetAddress" type="xs:token" maxOccurs="unbounded"/>
            <xs:element name="locality" type="xs:token"/>
            <xs:element name="region" type="xs:token"/>
            <xs:element name="postalCode" type="xs:token"/>
            <xs:element name="country" type="xs:token"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Skills">
        <xs:sequence>
            <xs:element name="skill" type="Collapsed" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="category" type="xs:token"/>
    </xs:complexType>

    <xs:complexType name="Interests">
        <xs:sequence>
            <xs:element name="interest" type="Collapsed" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="category" type="xs:token"/>
    </xs:complexType>

    <xs:complexType name="History">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="employment" type="Employment"/>
                <xs:element name="academic" type="Academic"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Employment">
        <xs:sequence>
            <xs:element name="position" type="xs:token"/>
            <xs:element name="employer" type="xs:token"/>
            <xs:element name="dates" type="DateRange"/>
            <xs:element name="description" type="TextBody"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DateRange">
        <!-- TODO tighten this down? -->
        <xs:attribute name="from" type="xs:token"/>
        <xs:attribute name="to" type="xs:token"/>
    </xs:complexType>

    <xs:complexType name="Academic">
        <xs:sequence>
            <xs:element name="institution" type="xs:token"/>
            <xs:element name="dates" type="DateRange"/>
            <xs:element name="concentration" type="AcademicConcentration" maxOccurs="unbounded"/>
            <xs:element name="achievement" type="AcademicAchievement" maxOccurs="unbounded"/>
            <xs:element name="description" type="TextBody" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AcademicConcentration">
        <xs:sequence>
            <xs:element name="subject" type="xs:token"/>
            <xs:element name="degree" type="DegreeLevel"/>
        </xs:sequence>
        <xs:attribute name="type" type="MajorMinor"/>
    </xs:complexType>

    <xs:simpleType name="DegreeLevel">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Generally BS, BA, but open to other values.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:token"/>
    </xs:simpleType>

    <xs:simpleType name="MajorMinor">
        <xs:restriction base="xs:string">
            <xs:enumeration value="major"/>
            <xs:enumeration value="minor"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="AcademicAchievement">
        <xs:sequence>
            <xs:element name="title" type="xs:token"/>
            <xs:element name="subject" type="xs:token" minOccurs="0"/>
            <xs:element name="description" type="Collapsed" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="type" type="AcademicAchievementType"/>
    </xs:complexType>

    <xs:simpleType name="AcademicAchievementType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="degree"/>
            <xs:enumeration value="award"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="TextBody">
        <xs:sequence>
            <xs:element name="para" type="Collapsed"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="Collapsed">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Processors MUST ensure strings are collapsed or that excess whitespace is
                otherwise ignored. Not all schema processors will augment instance
                documents in this way.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="collapse"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="HttpUri">
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https?://.*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="HttpsUri">
        <xs:restriction base="HttpUri">
            <xs:pattern value="https://.*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Email">
        <!-- this needs to be relaxed to some degree -->
        <!-- it is tweaked to accept my email address and '+' derivatives  -->
        <xs:restriction base="xs:string">
            <xs:pattern value="\w+([.]\w+)*([+]\w+)?[@]\w+[.]\w{2,}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Phone">
        <!-- hard to restrict -->
        <xs:restriction base="xs:token"/>
    </xs:simpleType>
</xs:schema>

=== bmatsuo/resume/resume.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://bmatsuo.github.io/Resume/xml-resume/xsl/html.xsl"?>
<resume xmlns="http://bmatsuo.github.io/xml-resume/0.3"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://bmatsuo.github.io/xml-resume/0.3 http://bmatsuo.github.io/xml-resume/0.3/schema/resume.xsd">
    <header>
        <name>Bryan Matsuo</name>
        <contact>
            <email>bryan.matsuo@gmail.com</email>
            <link href="https://github.com/bmatsuo">GitHub</link>
        </contact>
    </header>
    <skills category="Programming languages">
        <skill>Go</skill>
        <skill>Python</skill>
        <skill>Shell (bash)</skill>
        <skill>C/C++</skill>
        <skill>Ruby</skill>
        <skill>Lisp</skill>
        <skill>Lua</skill>
        <skill>Scala</skill>
        <skill>Haskell</skill>
    </skills>
    <skills category="Software and technology">
        <skill>Linux</skill>
        <skill>AWS</skill>
        <skill>Kubernetes/Helm</skill>
        <skill>Terraform</skill>
        <skill>Ansible</skill>
        <skill>Prometheus/Statsd/Graphite/Grafana</skill>
        <skill>gRPC/Protobuf</skill>
    </skills>
    <!--interests>
        <interest>Pragmatism</interest>
        <interest>Systems programming</interest>
        <interest>Infrastructure as code</interest>
    </interests-->
    <history>
        <employment>
            <position>Senior Software Engineer</position>
            <employer>Kunai</employer>
            <dates from="Jun 2025" to="Current"/>
            <description>
                <para>
                    Collaborating across teams in a large enterprise to update
                    and integrate software systems following a corporate
                    merger.  Writing documentation and comprehensive tests for
                    features and coordinating deployments to minimize adverse
                    impacts.
                </para>
            </description>
        </employment>
        <employment>
            <position>Go Software Engineer (Contract)</position>
            <employer>The Select Group (Comcast)</employer>
            <dates from="Aug 2023" to="Nov 2024"/>
            <description>
                <para>
                    Design and maintenance for a variety of serverless data
                    applications in Go leveraging AWS Lambda, Kinesis, Kafka,
                    NATS JetStream, DynamoDB, and Postgres.  Managing cloud
                    infrastructure with Terraform and Ansible. Developing
                    Grafana dashboards for real time monitoring of application
                    and infrastructure performance metrics.
                </para>
            </description>
        </employment>
        <employment>
            <position>Senior Software Engineer</position>
            <employer>Luther Systems, Ltd</employer>
            <dates from="Nov 2016" to="Jul 2023"/>
            <description>
                <para>
                    Development of an enterprise blockchain application
                    platform. Development and maintenance of Go microservices
                    and AWS Lambda functions connecting users and third-parties
                    with blockchains. Leading development of embedded Lisp
                    interpreter and Go SDK to streamline customer experiences.
                    Configuration and maintenance of system infrastructure in
                    AWS with Terraform and Ansible. Extensive Python and Bash
                    scripting for deploying and managing application
                    operations. Transitioning complex distributed systems from
                    AWS EC2 to Kubernetes using Helm. Implementation of
                    platform monitoring and alerting with Prometheus,
                    PagerDuty, and Grafana.
                </para>
            </description>
        </employment>
        <employment>
            <position>Senior Software Engineer</position>
            <employer>Janrain, Inc</employer>
            <dates from="Apr 2014" to="Nov 2015"/>
            <description>
                <para>
                    Primary development of backend data processing systems
                    using Go and Python along with related maintenance on
                    existing, related systems.  Development of service
                    packaging, deployment, and monitoring methodologies and
                    tooling to support them.
                </para>
            </description>
        </employment>
        <employment>
            <position>Software Engineer</position>
            <employer>Janrain, Inc</employer>
            <dates from="Feb 2012" to="Apr 2014"/>
            <description>
                <para>
                    Development of OpenID and OAuth integrations and backend
                    components for a user management offering.  Participant in
                    product design discussions. Responsible for meeting
                    deadlines with rapid customer rollout.  Responsible for
                    training the internal user base and facilitating adoption
                    of a new product.
                </para>
            </description>
        </employment>
        <academic>
            <institution>Univ of Califonia - Santa Cruz</institution>
            <dates from="Sept 2004" to="Mar 2009"/>
            <concentration type="major">
                <subject>Computer Science</subject>
                <degree>B.S.</degree>
            </concentration>
            <concentration type="major">
                <subject>Mathematics</subject>
                <degree>B.A.</degree>
            </concentration>
            <achievement>
                <title>Honors in Computer Science</title>
            </achievement>
            <achievement>
                <title>Highest honors in Mathematics</title>
            </achievement>
        </academic>
    </history>
</resume>

=== bmatsuo/resume/xml-resume/example/resume.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://bmatsuo.github.io/xml-resume/0.3/xsl/html.xsl"?>
<resume xmlns="http://bmatsuo.github.io/xml-resume/0.3"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://bmatsuo.github.io/xml-resume/0.3 http://bmatsuo.github.io/xml-resume/0.3/schema/resume.xsd">
    <header>
        <name>Lorem Ipsum Jr</name>
        <contact>
            <email>dolor@sit.amet</email>
            <phone>+1 555 555 5555</phone>
            <address>
                <street>123 consectetur adipiscing elit</street>
                <street>APT 4</street>
                <locality>Phasellus</locality>
                <region>TR</region>
                <postcode>73452</postcode>
                <country>Istique</country>
            </address>
            <link href="https://example.com/convallis">Ante</link>
            <link href="https://example.com/in/sed">Ultricies</link>
        </contact>
    </header>
    <objective>
        <para>
            Molestie id. Fusce est sem, accumsan sed consectetur ut, rhoncus ac
            eros. Etiam in adipiscing massa. Nunc vehicula mi ut risus pretium,
            at pretium nisi sodales.
        </para>
        <para>
            Duis sed magna vel orci tincidunt venenatis. Etiam nec condimentum
            arcu, at auctor nunc. Pellentesque a velit ipsum. Etiam ornare
            aliquam est ut placerat.
        </para>
    </objective>
    <skills category="Aenean">
        <skill>Pellentesque</skill>
        <skill>porttitor</skill>
        <skill>Turpis</skill>
        <skill>Ut</skill>
        <skill>Pretium</skill>
    </skills>
    <skills category="Nam Vel">
        <skill>Neque</skill>
        <skill>Aliquam</skill>
        <skill>Semper Orci</skill>
        <skill>Ac</skill>
        <skill>Ultrices</skill>
        <skill>Erat</skill>
        <skill>Aliquam Rhoncus</skill>
        <skill>Vestibulum</skill>
        <skill>Viverra</skill>
    </skills>
    <interests>
        <interest>Morbi</interest>
        <interest>Vitae dapibus nulla</interest>
        <interest>Vestibulum</interest>
        <interest>Odio quam</interest>
    </interests>
    <history>
        <employment>
            <position>Senior Tempor Non</position>
            <employer>Posuere Vehicula</employer>
            <dates from="Oct 2004" to="Dec 2012"/>
            <description>
                <para>
                    Molestie in ante. Aenean faucibus iaculis libero, ac tempor ipsum
                    volutpat non. Fusce lacinia, diam sed ornare volutpat, massa nunc
                    imperdiet lectus, nec rhoncus turpis turpis non enim. Etiam
                    imperdiet, nibh blandit fermentum imperdiet, tortor tortor
                    tristique justo, et ullamcorper odio quam eget neque.  Integer
                    consectetur urna quis est rutrum varius.
                </para>
            </description>
        </employment>
        <employment>
            <position>Cras Felis Orci</position>
            <employer>Posuere Vel Justo</employer>
            <dates from="Sept 2000" to="Aug 2004"/>
            <description>
                <para>
                    A, accumsan ultrices dolor. Suspendisse hendrerit ipsum vel lectus
                    ultricies, quis blandit neque blandit. Vestibulum ante ipsum
                    primis in faucibus orci luctus et ultrices posuere cubilia Curae;
                </para>
                <para>
                    Fusce purus dui, dapibus non libero mollis, cursus rutrum lectus.
                    Fusce volutpat at odio at interdum. Donec in ante sapien.
                </para>
            </description>
        </employment>
        <academic>
            <institution>Nam quis urna ut sapien</institution>
            <dates from="Aug 1994" to="May 1999"/>
            <concentration type="major">
                <subject>Aretium Laoreet</subject>
                <degree>I.S.</degree>
            </concentration>
            <concentration type="minor">
                <subject>Amet Fermentum</subject>
                <degree/>
            </concentration>
            <achievement>
                <title>Etiam nulla sapien</title>
            </achievement>
        </academic>
    </history>
</resume>
